name: setup-tq
description: Setup GitHub Actions with tq (tomlq)
author: remarkablemark

inputs:
  version:
    description: Version
    required: false
    default: 0.2.2
  cache:
    description: Enable caching
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Cache Cargo dependencies
      if: inputs.cache == 'true'
      uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-tq-${{ inputs.version }}
        restore-keys: |
          ${{ runner.os }}-cargo-tq-

    - name: Check binary
      id: check
      shell: bash
      run: |
        if command -v tq >/dev/null 2>&1 && [[ "$(tq --version)" == *"$VERSION" ]]; then
          echo 'installed=true' >> $GITHUB_OUTPUT
        fi
      env:
        VERSION: ${{ inputs.version }}

    # https://github.com/marketplace/actions/install-cargo-binstall
    - name: Install Binstall
      if: steps.check.outputs.installed != 'true'
      uses: cargo-bins/cargo-binstall@v1.17.4

    # https://github.com/cryptaliagy/tomlq
    - name: Install tq
      if: steps.check.outputs.installed != 'true'
      shell: bash
      run: cargo binstall -y tomlq@$VERSION --force
      env:
        VERSION: ${{ inputs.version }}

branding:
  icon: type
  color: white
